name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

    - name: Terraform Init and Validate
      run: terraform init
      
    - name: Terraform validate
      run: terraform validate

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Plan
      run: terraform plan -out=plan.out

    - name: Archive Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: plan.out
   
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

  apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3

    - name: Download Terraform Initialization Data
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
        path: plan.out

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Show
      run: terraform show plan.out
    
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
